# Generated by Django 4.0.4 on 2022-05-18 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_end_country_trip_start_country'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('start_date_and_time__gte', datetime.datetime(2022, 5, 18, 12, 18, 21, 243952, tzinfo=utc))), name='start_date_time'),
        ),
    ]
