# Generated by Django 4.0.4 on 2022-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_trip_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='places_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
